### ISSUE TITLE
WARN - Thread 11 Bug

### ISSUE THREAD

**Issue by goldenkuky209** [OsipXD/RPGInventory#177] opened 2022-01-02 11:30 UTC
I get this warning everytime i close the server:
i dont know what it means or where its coming from.

02.01 11:10:12 [Server] WARN Exception in thread "Thread-11" java.lang.IllegalStateException: zip file closed
02.01 11:10:12 [Server] WARN at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
02.01 11:10:12 [Server] WARN at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
02.01 11:10:12 [Server] WARN at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
02.01 11:10:12 [Server] WARN at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
02.01 11:10:12 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
02.01 11:10:12 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
02.01 11:10:12 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
02.01 11:10:12 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
02.01 11:10:12 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
02.01 11:10:12 [Server] WARN at shade.ru.endlesscode.rpginventory.sentry.protocol.User.<init>(User.java:48)
02.01 11:10:12 [Server] WARN at shade.ru.endlesscode.rpginventory.sentry.Scope.<init>(Scope.java:90)
02.01 11:10:12 [Server] WARN at shade.ru.endlesscode.rpginventory.sentry.Stack$StackItem.<init>(Stack.java:28)
02.01 11:10:12 [Server] WARN at shade.ru.endlesscode.rpginventory.sentry.Stack.<init>(Stack.java:57)
02.01 11:10:12 [Server] WARN at shade.ru.endlesscode.rpginventory.sentry.Hub.clone(Hub.java:528)
02.01 11:10:12 [Server] WARN at shade.ru.endlesscode.rpginventory.sentry.Sentry.getCurrentHub(Sentry.java:44)
02.01 11:10:12 [Server] WARN at shade.ru.endlesscode.rpginventory.sentry.Sentry.flush(Sentry.java:496)
02.01 11:10:12 [Server] WARN at shade.ru.endlesscode.rpginventory.sentry.HubAdapter.flush(HubAdapter.java:151)
02.01 11:10:12 [Server] WARN at shade.ru.endlesscode.rpginventory.sentry.ShutdownHookIntegration.lambda$register$0(ShutdownHookIntegration.java:33)
02.01 11:10:12 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by osipxd** [comment] 2022-04-19 06:46
Duplicate of #173

**Closed as completed by osipxd** 2022-04-19 06:46 UTC
