### ISSUE TITLE
Offhand item dupe

### ISSUE THREAD

**Issue by GhoulBread** [OsipXD/RPGInventory#172] opened 2021-03-05 11:02 UTC
Hi, is me angin, this bug still not fix...
It is click button F to put item in off-hand, And click the button F on your any air inventory. It can copy item.
I make a video. Hope you can fix it. If you need more detail. Please tell me. (sorry, my English is not good)
https://youtu.be/4nIBtP0d74k

**Comment by TheCiROMG** [comment] 2021-11-20 23:27
Your partner's Rage made me laugh, I've been testing this plugin (I'm not the dev) but I want to leave this comment

Look at the configuration file of the SLOTS, THAT THE NAME IS NOT REPEATED

What does it mean?

slots:
   backpack:
   backpack: <--- this does not have to happen, to solve it, just put a number

slots:
   backpack:
   backpack2:

Also check if it happens with a mod or plugin, so you ask the devs of it, to implement a small compatibility and to try to solve it themselves, if it cannot be solved on this side

Also check that the number is correct, and also check both plugins if they have some "protection" to fast clicks

**Comment by osipxd** [comment] 2022-04-19 16:56
Duplicate of #176

**Closed as completed by osipxd** 2022-04-19 16:56 UTC
